# -*- coding: utf-8 -*-
"""eda_yelp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Vh21ABgituGJHgElFnmlC7yQmS-uTSw
"""

import pandas as pd

